### ISSUE TITLE
Type hint error

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp-guide-examples#11]
Hi, I find a type hint error when I read the guide. In the path of `allennlp-guide-examples\quick_start\my_text_classifier`, the 25 line of the file `sim_classifier.py`, the parameter `text` is the type of `TextFieldTensors`, namely `Dict[str, Dict[str, torch.Tensor]]`, instead of `Dict[str, torch.Tensor]`. 

Because the type hint in Python is only hint and Python will not inspect whether the type is correct,  this error will not influence the execution of the code. While I think the output type of `TextField` is the important difference between 0.9 and 1.0, the wrong type hint error may lead to misunderstandings.

![image](https://user-images.githubusercontent.com/39905704/86350838-e23cb600-bc95-11ea-9c23-e6763768e935.png)

**Comment by matt-gardner** [comment]
Yes, you're right.  Care to submit a PR to fix this?

**Comment by Zessay** [comment]
Yes, it's my pleasure.
