### ISSUE TITLE
Does the training script automatically uses GPU? or we need to write some code to make sure it uses GPU if available.

### ISSUE THREAD

**Issue by abubakar-ucr** [allenai/allennlp-guide-examples#17]
Does the training script automatically uses GPU? or we need to write some code to make sure it uses GPU if available.

**Comment by matt-gardner** [comment]
Are you asking about using `allennlp train`, or about using a separate script?  `allennlp train` will auto-detect GPUs and use it if available as of allennlp version 1.1.  If you are using your own script, you need to handle moving the model to the GPU yourself, before you construct the optimizer and the trainer.  This is not done in the example `train.py` script in this repo.

**Comment by abubakar-ucr** [comment]
Thanks. I am using version 1.0. so, I believe doing:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model = model.to(device) 
before constructing the optimizer and the trainer, and passing to trainer the argument 'cuda_device= device' would do it. I am closing it. Thanks.
