### ISSUE TITLE
ImportError: cannot import name 'DataLoader' from 'allennlp.data'

### ISSUE THREAD

**Issue by grantgasser** [allenai/allennlp-guide-examples#8]
Hey!

I'm receiving the following error when trying to run the `train.py` script: 

```
ImportError: cannot import name 'DataLoader' from 'allennlp.data' (/Users/grantgasser/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/allennlp/data/__init__.py)
```

I'm on mac using Python 3.7 and I ran `pip install allennlp` in my conda environment after cloning the master branch of this course.

**Comment by matt-gardner** [comment]
You'll need to have a recent release of allennlp.  I'm guessing that if you look at the allennlp version, you're on 0.9.  You'll need at least 1.0.0rc4.  It's a pre-release, so it doesn't get installed with `pip install` unless you do `--pre`.

**Comment by grantgasser** [comment]
That worked! I ran `pip uninstall allennlp` and then `pip install allennlp --pre`.

**Comment by matt-gardner** [comment]
It's just a difference of where the scripts are designed to be run from. Glad you got it working!
